development:
  adapter: postgresql
  database: sample_app-dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sample_app-tst
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sample_app-pro
  pool: 5
  timeout: 5000
